import { useState, useEffect } from 'react';

import api from '../api';
import { TrendingUp, AlertCircle, DollarSign, Activity } from 'lucide-react';

interface OverviewData {
  revenue_at_risk: number;
  net_incremental_recovery: number;
  total_incidents: number;
  active_cases: number;
}

export default function Overview() {
  const [data, setData] = useState<OverviewData | null>(null);

  useEffect(() => {
    api.get('/overview').then(res => setData(res.data)).catch(console.error);
  }, []);

  return (
    <div className="p-8">
      <h2 className="text-2xl font-bold text-slate-800 mb-6">Executive Overview</h2>
      
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        <div className="bg-white p-6 rounded-lg shadow-sm border border-slate-200">
          <div className="flex items-center text-slate-500 mb-4">
            <DollarSign className="w-5 h-5 mr-2" />
            <h3 className="font-medium">Revenue at Risk</h3>
          </div>
          <p className="text-3xl font-bold text-slate-800">
            ${data?.revenue_at_risk?.toLocaleString() ?? '---'}
          </p>
        </div>

        <div className="bg-white p-6 rounded-lg shadow-sm border border-slate-200">
          <div className="flex items-center text-blue-600 mb-4">
            <TrendingUp className="w-5 h-5 mr-2" />
            <h3 className="font-medium">Net Incremental Recovery</h3>
          </div>
          <p className="text-3xl font-bold text-blue-700">
            ${data?.net_incremental_recovery?.toLocaleString() ?? '---'}
          </p>
        </div>

        <div className="bg-white p-6 rounded-lg shadow-sm border border-slate-200">
          <div className="flex items-center text-rose-500 mb-4">
            <AlertCircle className="w-5 h-5 mr-2" />
            <h3 className="font-medium">Total Incidents</h3>
          </div>
          <p className="text-3xl font-bold text-slate-800">
            {data?.total_incidents ?? '---'}
          </p>
        </div>

        <div className="bg-white p-6 rounded-lg shadow-sm border border-slate-200">
          <div className="flex items-center text-emerald-500 mb-4">
            <Activity className="w-5 h-5 mr-2" />
            <h3 className="font-medium">Active Cases</h3>
          </div>
          <p className="text-3xl font-bold text-slate-800">
            {data?.active_cases ?? '---'}
          </p>
        </div>
      </div>

      <div className="bg-blue-50 border-l-4 border-blue-500 p-4 rounded-r-lg">
        <h4 className="font-semibold text-blue-800 mb-2">Important Clarification</h4>
        <p className="text-blue-700">
          <strong>Gross Recovery ≠ Incremental Recovery.</strong> Our system focuses on <em>Incremental Recovery</em>—the actual value generated by our actions that would not have occurred naturally. Gross recovery includes customers who would have recovered without any intervention.
        </p>
      </div>
    </div>
  );
}
